---
address-autofill-edit:
  description: This property defines if the address editing is enabled in Settings
  hasExposure: true
  exposureDescription: ""
  variables:
    status:
      type: boolean
      description: "If true, we will allow user to edit the address"
address-bar-menu-feature:
  description: "This property determines if we show the new address bar menu entry or the toolbar menu in settings\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    status:
      type: boolean
      description: "If true, we will show the new address bar menu entry"
appearance-menu-feature:
  description: "This property determines if we show the new appearance menu entry or the old theme settings\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    status:
      type: boolean
      description: "If true, we will show the new appearance menu entry"
deeplink-optimization-refactor-feature:
  description: "The feature flag to manage the rollout of deeplink optimization feature.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Variable description\n"
default-zoom-feature:
  description: "The feature flag to manage the rollout of default zoom feature.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If true, page zoom settings and default zoom feature are shown\n"
download-live-activities-feature:
  description: "Download Live Activities Feature\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If true, the download live activities feature is enabled\n"
felt-privacy-feature:
  description: The feature that enhances private browsing mode
  hasExposure: true
  exposureDescription: ""
  variables:
    felt-deletion-enabled:
      type: boolean
      description: "If true, enable Felt Deletion part of Felt Privacy"
    simplified-ui-enabled:
      type: boolean
      description: "If true, enable simplified UI part of Felt Privacy"
firefox-suggest-feature:
  description: Configuration for the Firefox Suggest feature.
  hasExposure: true
  exposureDescription: ""
  variables:
    available-suggestions-types:
      type: json
      description: "A map of suggestion types to booleans that indicate whether or not the provider should return suggestions of those types.\n"
    status:
      type: boolean
      description: "Whether the feature is enabled. When Firefox Suggest is enabled, Firefox will download and store new search suggestions in the background, and show additional Search settings to control which suggestions appear in the awesomebar. When Firefox Suggest is disabled, Firefox will not download new suggestions, and hide the additional Search settings.\n"
general-app-features:
  description: The feature that contains feature flags for the entire application
  hasExposure: true
  exposureDescription: ""
  variables:
    report-site-issue:
      type: json
      description: This property defines whether or not the feature is enabled
hnt-sponsored-shortcuts-feature:
  description: This feature manages the visibility of sponsored shortcuts on the homepage
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Setting 'enabled' to false will hide sponsored shortcuts on the homepage and disable the respective toggle in the homepage settings"
hnt-top-sites-visual-refresh-feature:
  description: This feature manages the top sites visual refresh.
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: Determines whether the top sites visual refresh is shown.
homepage-rebuild-feature:
  description: "This feature is for managing the roll out of the Homepage rebuild feature\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If true, enables the feature\n"
homepage-redesign-feature:
  description: "This feature is for managing the roll out of the Homepage New Tab Redesign feature.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature.\n"
    search-bar:
      type: boolean
      description: "If true, enables the search bar feature on homepage for users.\n"
    stories-redesign:
      type: boolean
      description: "If true, enables the stories section redesign on homepage, which also includes the removal of other sections (i.e. jump back in, bookmarks)\n"
logins-verification:
  description: "Feature that enables the logins verification logic.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    logins-verification-enabled:
      type: boolean
      description: "Whether the logins verification logic is enabled. When enabled, an attempt will be made to decrypt all stored logins when sync is enabled. If a login cannot be decrypted, it will be locally deleted to unblock syncing.\n"
menu-refactor-feature:
  description: "Controls the menu refactor feature\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Controls which menu users will see\n"
    menu-default-browser-banner:
      type: boolean
      description: "If true, enables the menu Make Firefox your default banner, on top of the menu.\n"
    menu-hint:
      type: boolean
      description: "If true, enables the menu contextual hint.\n"
    menu-redesign:
      type: boolean
      description: "If true, enables the menu redesign.\n"
    menu-redesign-hint:
      type: boolean
      description: "If true, enables the menu contextual hint for menu redesign.\n"
messaging:
  description: "The in-app messaging system\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    actions:
      type: json
      description: A growable map of action URLs.
    message-under-experiment:
      type: string
      description: "Deprecated. Please use \"experiment\": \"{experiment}\" instead."
    messages:
      type: json
      description: "A growable collection of messages, where the Key is the message identifier and the value is its associated MessageData.\n"
    on-control:
      type: string
      description: What should be displayed when a control message is selected.
      enum:
        - show-next-message
        - show-none
    styles:
      type: json
      description: "A map of styles to configure message appearance.\n"
    triggers:
      type: json
      description: "A collection of out the box trigger expressions. Each entry maps to a valid JEXL expression.\n"
    ~~experiment:
      type: string
      description: Not to be set by experiment.
microsurvey-feature:
  description: "A feature that shows the microsurvey for users to interact with and submit responses.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If true, the feature is active.\n"
native-error-page-feature:
  description: "This feature is for managing the roll out of the native error page feature\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If true, the feature is active.\n"
    no_internet_connection_error:
      type: boolean
      description: "This feature is for managing the roll out of the no interet connection native error page feature\n"
onboarding-framework-feature:
  description: "The new onboarding framework feature that will allow onboarding to be experimentable through initial experiments.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    cards:
      type: json
      description: "The list of available cards for onboarding.\n"
    conditions:
      type: json
      description: "A collection of out the box conditional expressions to be used in determining whether a card should show or not. Each entry maps to a valid JEXL expression.\n"
    dismissable:
      type: boolean
      description: "Whether or not the entire onboarding is dismissable by pressing an X at the top right corner of the screen.\n"
    enableModernUi:
      type: boolean
      description: "Toggle between legacy (false) and modern (true) UI variants.\n"
pdf-refactor-feature:
  description: "The feature flag to manage the roll out of the pdf refactor feature.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature.\n"
rating-prompt-feature:
  description: "This feature enables the rating prompt so we ask in-app rating to users\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the rating prompt\n"
revert-unsafe-continuations-refactor:
  description: "A feature flag to wrap reverting the unsafe continuations usage in the app. Unsafe continuations were used in response to an early 2025 incident when iOS 18.0 (possibly beta only) crashed on checked continuations (both regular and throwing).\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If true, revert unsafe continuations usage back to normal checked continuations usage.\n"
search:
  description: "Configuring the functionality to do with search. This will be separated into smaller sub-features in later releases.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    awesome-bar:
      type: json
      description: Configuring the awesome bar.
search-engine-consolidation-feature:
  description: "This feature is for managing the roll out of Search Engine Consolidation support in iOS\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature\n"
splash-screen:
  description: "A feature that extends splash screen duration, allowing additional data fetching time for the app's initial run.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If true, the feature is active.\n"
    maximum_duration_ms:
      type: int
      description: "The maximum amount of time in milliseconds the splashscreen will be visible while waiting for initialization calls to complete.\n"
spotlight-search:
  description: Add pages as items findable with Spotlight.
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If this is true, then on each page load adds a new item to Spotlight."
    icon-type:
      type: string
      description: "The icon that is displayed next to the item in the search results. If this is `null`, then no icon is displayed.\n"
    keep-for-days:
      type: int
      description: "Number of days to keep the item before automatic deletion. If this is left `null`, then it is left to iOS's default.\n"
    searchable-content:
      type: string
      description: "The text content that is made searchable. If this is `null` then no additional content is used, and only the title and URL will be used.\n"
start-at-home-feature:
  description: This feature is for experimenting with opening screen
  hasExposure: true
  exposureDescription: ""
  variables:
    setting:
      type: string
      description: This property provides a default setting for the start at home feature
      enum:
        - afterFourHours
        - always
        - disabled
summarizer-feature:
  description: "This feature enables the summarizer feature.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the summarizer feature.\n"
tab-tray-ui-experiments:
  description: "The tab tray will undergo some UI experimentation to test potential improvements.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If true, enables the tab tray UI experiments.\n"
tabTrayFeature:
  description: The tab tray screen that the user goes to when they open the tab tray.
  hasExposure: true
  exposureDescription: ""
  variables:
    sections-enabled:
      type: json
      description: "This property provides a lookup table of whether or not the given section should be enabled. If the section is enabled, it should be toggleable in the settings screen, and on by default."
toolbar-refactor-feature:
  description: "This feature is for managing the roll out of the Toolbar refactor feature\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature\n"
    layout:
      type: string
      description: "The type of layout of the toolbars.\n"
    minimal_address_bar:
      type: boolean
      description: "Enables minimal address bar mode on scroll to ensure the url is always visible.\n"
    navigation_hint:
      type: boolean
      description: "If true, enables the navigation contextual hint.\n"
    one_tap_new_tab:
      type: boolean
      description: "If true, enables the one tap new tab feature for users.\n"
    swiping_tabs:
      type: boolean
      description: "Enables swipe gestures to switch between browser tabs.\n"
    toolbar_update_hint:
      type: boolean
      description: "If true, enables the toolbar update contextual hint.\n"
    translucency:
      type: boolean
      description: "Enables translucency for toolbars.\n"
    unified_search:
      type: boolean
      description: "Enables the unified search feature.\n"
tos-feature:
  description: "This feature is for managing the roll out of the ToS (Term of Service) implementation\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    status:
      type: boolean
      description: "Enables the feature\n"
tou-feature:
  description: "This feature is for managing the rollout of the Terms of Use (ToU) implementation.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    status:
      type: boolean
      description: "Enables the feature\n"
tracking-protection-refactor:
  description: "The Enhanced Tracking Protection refactor\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Whether the Enhanced Tracking Protection refactor is enabled or not\n"
unified-ads:
  description: "This property is for managing the roll out of the unified ads API\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If true, we will enable user to use the unified ads API\n"
updated-password-manager-feature:
  description: "This property determines if we use the updated password manager or the legacy one.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    status:
      type: boolean
      description: "If true, firefox will use the  the updated password manager."
web-engine-integration-refactor:
  description: "The feature flag to manage the roll out of the integration of WebEngine into Firefox.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature.\n"
