"""
This type stub file was generated by pyright.
"""

from .scalars import Scalar

class Date(Scalar):
    """
    The `Date` scalar type represents a Date
    value as specified by
    [iso8601](https://en.wikipedia.org/wiki/ISO_8601).
    """

    @staticmethod
    def serialize(date): ...
    @classmethod
    def parse_literal(cls, node): ...
    @staticmethod
    def parse_value(value): ...

class DateTime(Scalar):
    """
    The `DateTime` scalar type represents a DateTime
    value as specified by
    [iso8601](https://en.wikipedia.org/wiki/ISO_8601).
    """

    @staticmethod
    def serialize(dt): ...
    @classmethod
    def parse_literal(cls, node): ...
    @staticmethod
    def parse_value(value): ...

class Time(Scalar):
    """
    The `Time` scalar type represents a Time value as
    specified by
    [iso8601](https://en.wikipedia.org/wiki/ISO_8601).
    """

    @staticmethod
    def serialize(time): ...
    @classmethod
    def parse_literal(cls, node): ...
    @classmethod
    def parse_value(cls, value): ...
