"""
This type stub file was generated by pyright.
"""

from ..utils.orderedtype import OrderedType

class MountedType(OrderedType):
    @classmethod
    def mounted(cls, unmounted):  # -> Self@MountedType:
        """
        Mount the UnmountedType instance
        """
        ...
