"""
This type stub file was generated by pyright.
"""

from .unmountedtype import UnmountedType

class Structure(UnmountedType):
    """
    A structure is a GraphQL type instance that
    wraps a main type with certain structure.
    """

    def __init__(self, of_type, *args, **kwargs) -> None: ...
    @property
    def of_type(self): ...
    def get_type(self):  # -> Self@Structure:
        """
        This function is called when the unmounted type (List or NonNull instance)
        is mounted (as a Field, InputField or Argument)
        """
        ...

class List(Structure):
    """
    List Modifier

    A list is a kind of type marker, a wrapping type which points to another
    type. Lists are often created within the context of defining the fields of
    an object type.

    List indicates that many values will be returned (or input) for this field.

    .. code:: python

        from graphene import List, String

        field_name = List(String, description="There will be many values")
    """

    def __str__(self) -> str: ...
    def __eq__(self, other) -> bool: ...

class NonNull(Structure):
    """
    Non-Null Modifier

    A non-null is a kind of type marker, a wrapping type which points to another
    type. Non-null types enforce that their values are never null and can ensure
    an error is raised if this ever occurs during a request. It is useful for
    fields which you can make a strong guarantee on non-nullability, for example
    usually the id field of a database row will never be null.

    Note: the enforcement of non-nullability occurs within the executor.

    NonNull can also be indicated on all Mounted types with the keyword argument ``required``.

    .. code:: python

        from graphene import NonNull, String

        field_name = NonNull(String, description='This field will not be null')
        another_field = String(required=True, description='This is equivalent to the above')

    """

    def __init__(self, *args, **kwargs) -> None: ...
    def __str__(self) -> str: ...
    def __eq__(self, other) -> bool: ...
