"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

"""Utilities used by the message signing serializer."""
__all__ = ("get_digest_algorithm", "reraise_errors")

def get_digest_algorithm(digest=...):  # -> Any:
    """Convert string to hash object of cryptography library."""
    ...

@contextmanager
def reraise_errors(msg=..., errors=...):  # -> Generator[None, None, None]:
    """Context reraising crypto errors as :exc:`SecurityError`."""
    ...
