"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Any, Callable, Union

from django.http.response import HttpResponse
from sentry_sdk import Hub, _functools
from sentry_sdk._types import MYPY
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware

"""
Instrumentation for Django 3.0

Since this file contains `async def` it is conditionally imported in
`sentry_sdk.integrations.django` (depending on the existence of
`django.core.handlers.asgi`.
"""
if MYPY: ...

def patch_django_asgi_handler_impl(cls: Any) -> None: ...
def patch_get_response_async(cls: Any, _before_get_response: Any) -> None: ...
def patch_channels_asgi_handler_impl(cls: Any) -> None: ...
def wrap_async_view(hub: Hub, callback: Any) -> Any: ...
