# Generated by Django 5.2.14 on 2026-07-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_fix_indonesian_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteflag',
            name='extra_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siteflag',
            name='name',
            field=models.CharField(choices=[('ADVERTISE_DEVTOOLS', 'Advertise nimbus-devtools')], max_length=255, unique=True),
        ),
    ]
