# Generated by Django 5.2.16 on 2026-08-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_siteflag_extra_data_alter_siteflag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteflag',
            name='name',
            field=models.CharField(choices=[('ADVERTISE_DEVTOOLS', 'Advertise nimbus-devtools'), ('NEW_DELIVERY_MENU', "Enable the 'New Delivery' menu")], max_length=255, unique=True),
        ),
    ]
