"""
This type stub file was generated by pyright.
"""

import logging

import requests
from kinto_http.client import AsyncClient, Client
from kinto_http.endpoints import Endpoints
from kinto_http.exceptions import (
    BucketNotFound,
    CollectionNotFound,
    KintoBatchException,
    KintoException,
)
from kinto_http.session import Session, create_session

logger = ...
__all__ = (
    "BearerTokenAuth",
    "Endpoints",
    "Session",
    "AsyncClient",
    "Client",
    "create_session",
    "BucketNotFound",
    "CollectionNotFound",
    "KintoException",
    "KintoBatchException",
)

class BearerTokenAuth(requests.auth.AuthBase):
    def __init__(self, token, type=...) -> None: ...
    def __call__(self, r): ...
