[metrics]
daily = ["retained"]
weekly = ["retained", "active_hours", "days_of_use", "search_count", "serp_ad_clicks"]
overall = ["active_hours", "days_of_use", "search_count", "serp_ad_clicks"]

[metrics.retained]
select_expression = "COALESCE(COUNT(document_id), 0) > 0"
data_source = "baseline"

[metrics.retained.statistics]
binomial = {}

##

[metrics.active_hours]
select_expression = "COALESCE(SUM(metrics.timespan.glean_baseline_duration.value), 0) / 3600.0"
data_source = "baseline"

[metrics.active_hours.statistics]
deciles = {}
bootstrap_mean = {}

##

[metrics.days_of_use]
friendly_name = "Days of use"
description = "The number of days in an observation window that clients used the browser."
select_expression = "COUNT(DISTINCT DATE(submission_timestamp))"
data_source = "baseline"

[metrics.days_of_use.statistics]
deciles = {}
bootstrap_mean = { drop_highest = 0 }
empirical_cdf = {}

##

[metrics.search_count]
friendly_name = "SAP search count"
description = "Number of searches performed through a Search Access Point."
select_expression = "{{agg_sum('search_count')}}"
data_source = "mobile_search_clients_engines_sources_daily"

[metrics.search_count.statistics]
deciles = {}
bootstrap_mean = {}

##

[metrics.serp_ad_clicks]
friendly_name = "Ad Clicks"
description = "Number of ad clicks on a search engine results page."
select_expression = "{{agg_sum('ad_click')}}"
data_source = "mobile_search_clients_engines_sources_daily"

[metrics.serp_ad_clicks.statistics]
deciles = {}
bootstrap_mean = {}
##

[data_sources.mobile_search_clients_engines_sources_daily]
from_expression = "mozdata.search.mobile_search_clients_engines_sources_daily"
experiments_column_type = "simple"
