# This defines the default metrics and statistics calculated for each experiment

[metrics]
daily = ["retained", "unenroll"]

weekly = [
  "active_hours",
  "ad_clicks",
  "days_of_use",
  "retained",
  "uri_count",
  "search_count",
  "qualified_cumulative_days_of_use",
]

overall = [
  "active_hours",
  "ad_clicks",
  "days_of_use",
  "organic_search_count",
  "search_count",
  "searches_with_ads",
  "separate_search_engine",
  "tagged_search_count",
  "tagged_follow_on_search_count",
  "uri_count",
  "qualified_cumulative_days_of_use",
]


[metrics.active_hours.statistics.bootstrap_mean]
[metrics.active_hours.statistics.deciles]

[metrics.ad_clicks.statistics.bootstrap_mean]
[metrics.ad_clicks.statistics.deciles]

[metrics.days_of_use.statistics.bootstrap_mean]
drop_highest = 0

[metrics.days_of_use.statistics.deciles]
[metrics.days_of_use.statistics.empirical_cdf]

[metrics.organic_search_count.statistics.bootstrap_mean]
[metrics.organic_search_count.statistics.deciles]

[metrics.retained]
select_expression = "COALESCE(SUM(pings_aggregated_by_this_row), 0) > 0"
data_source = "clients_daily"
friendly_name = "Retained"
description = "Records whether a client submitted any pings (i.e. used Firefox)."

[metrics.retained.statistics.binomial]

[metrics.uri_count.statistics.bootstrap_mean]
[metrics.uri_count.statistics.deciles]

[metrics.search_count.statistics.bootstrap_mean]
[metrics.search_count.statistics.deciles]

[metrics.searches_with_ads.statistics.bootstrap_mean]
[metrics.searches_with_ads.statistics.deciles]

[metrics.separate_search_engine]
select_expression = "COALESCE(ANY_VALUE(default_search_engine != default_private_search_engine), false)"
data_source = "search_clients_engines_sources_daily"
friendly_name = "Split PBM search engine"
description = "Indicates whether the client configured separate search engines for regular browsing and private browsing mode."
[metrics.separate_search_engine.statistics.binomial]

[metrics.tagged_search_count.statistics.bootstrap_mean]
[metrics.tagged_search_count.statistics.deciles]

[metrics.tagged_follow_on_search_count.statistics.bootstrap_mean]
[metrics.tagged_follow_on_search_count.statistics.deciles]

[metrics.unenroll.statistics.binomial]

[metrics.qualified_cumulative_days_of_use.statistics.bootstrap_mean]
[metrics.qualified_cumulative_days_of_use.statistics.deciles]
