friendly_name = "FxA Access Method"
description = "Did they use the Account Icon or Menu to open FxA"

[metrics.fxa_toolbar_menu_button_users_clicks]
select_expression = """(
  SUM(
    COALESCE(mozfun.map.get_key(payload.processes.parent.keyed_scalars.browser_ui_interaction_nav_bar, 'fxa-toolbar-menu-button'),0) 
  )
)"""
data_source = "main"
friendly_name = "Clicks on the account button from users"
description = """
   Counts the number of times  user clicks on the account button
"""

[metrics.fxa_toolbar_menu_button_users_clicks.statistics.bootstrap_mean]


[metrics.fxa_avatar_menu_clicks]
friendly_name = "Clicks on the sign in option on the PXI panel"
description = "Number of times user clicks on fxa_avatar_menu"
select_expression = """
      COALESCE(COUNTIF(
         event_method= 'click'
         AND event_object = 'login'
         AND event_category = 'fxa_avatar_menu'
      ),0)
"""
data_source = "fxa_avatar_menu_events"
statistics = { bootstrap_mean = {} }

[data_sources]

[data_sources.fxa_avatar_menu_events]
from_expression = '''(SELECT * FROM `mozdata.telemetry.events` WHERE event_category = 'fxa_avatar_menu')'''
experiments_column_type = "native"
friendly_name = "FxA Avatar Menu Events"
description = "Events Ping filtered to only include FxA Avatar Menu event category"
