friendly_name = "DO NOT USE - SERP Metrics"
description = "Metrics for SERP interactions derived from Glean SERP events - this outcome has been deprecated, do not use!"

[metrics.serp_impressions]
friendly_name = "no-op serp impressions"
description = "zeroing out serp impressions to prevent timeouts with outcome metric"
select_expression = "SUM(0)"
data_source = "noop_ds"

[metrics.serp_impressions.statistics.bootstrap_mean]

[data_sources]

[data_sources.noop_ds]
from_expression = """(
    SELECT
        '1234' AS client_id,
        '12345' AS profile_group_id,
        DATE('2022-01-01') AS submission_date
)"""
experiments_column_type = "none"
friendly_name = "No-Op"
description = "No-op that creates the required columns"
