friendly_name = "Sponsored Tiles"
description = "Interaction metrics for sponsored tiles."

[metrics.sponsored_tiles_disabled.statistics.binomial]
[metrics.any_sponsored_tiles_dismissals.statistics.binomial]

[metrics.sponsored_tiles_dismissals.statistics.bootstrap_mean]
[metrics.sponsored_tiles_dismissals.statistics.deciles]

[metrics.sponsored_tiles_dismissals_pos1_2.statistics.bootstrap_mean]
[metrics.sponsored_tiles_dismissals_pos1_2.statistics.deciles]

[metrics.sponsored_tile_clicks.statistics.bootstrap_mean]
[metrics.sponsored_tile_clicks.statistics.deciles]

[metrics.sponsored_tile_impressions.statistics.bootstrap_mean]
[metrics.sponsored_tile_impressions.statistics.deciles]
