friendly_name = "Stricter PBM"
description = """
Metrics related to the Stricter PBM initiative
working toward true anonymous browsing. Currently
contains ETP Disablement, URI reloads, and 
Share of URIs opened in PBM
"""

[metrics.etp_disablement]
select_expression = """(
    COALESCE(COUNTIF(
        event_category = 'security.ui.protectionspopup' AND 
        event_method = 'click' AND 
        event_object = 'etp_toggle_off'        
    ), 0)
)"""
data_source = "events"
friendly_name = "ETP Disablement"

[metrics.etp_disablement.statistics.bootstrap_mean]


[metrics.uri_reloads]
select_expression = 'COALESCE(SUM(payload.processes.parent.scalars.browser_engagement_tab_reload_count), 0)'
data_source = 'main'
friendly_name = "URI Reloads"

[metrics.uri_reloads.statistics.bootstrap_mean]


[metrics.share_of_uri_count_in_pbm]
select_expression = "sum(total_uri_count_private_mode)/(sum(total_uri_count_private_mode)+sum(total_uri_count_normal_mode))"
data_source = "clients_daily"
friendly_name = "Proportion of URIs coming from PBM"

[metrics.share_of_uri_count_in_pbm.statistics.bootstrap_mean]
