friendly_name = "Webcompat"
description = """
Metrics typically influenced by webcompat-breakages.
Currently contains ETP Disablement, URI reloads,
webcompat reporting panel impressions,
and webcompat reporting panel uses.
"""

[metrics.etp_disablement.statistics.bootstrap_mean]
[metrics.etp_disablement.statistics.deciles]

[metrics.tab_reload_count.statistics.bootstrap_mean]
[metrics.tab_reload_count.statistics.deciles]

[metrics.site_breakage_impressions.statistics.bootstrap_mean]
[metrics.site_breakage_impressions.statistics.deciles]

[metrics.site_breakage_uses.statistics.bootstrap_mean]
[metrics.site_breakage_uses.statistics.deciles]
