"""
This type stub file was generated by pyright.
"""

import json
import pkgutil
from dataclasses import dataclass
from pathlib import Path

import jsonschema

_validator_cache = ...
_data_cache = ...
NimbusSchemaNotFoundError = FileNotFoundError

class NimbusValidationError(Exception):
    def __init__(self, error_iterator) -> None: ...

def check_schema(schema_name: str, instance: any) -> bool:
    """
    Check if `instance` matches the schema named `schema_name`.

    Returns `True` if it does. If it does not match the schema,
    `mozilla_nimbus_shared.NimbusValidationError` is thrown. It contains an
    attribute `.errors` that detail all the ways the data does not match the
    schema.

    If the schema name given does not refer to a known schema, then a
    `mozilla_nimbus_shared.NimbusSchemaNotFoundError` exception is thrown.
    """
    ...

def get_data() -> dict:
    """Load all the Nimbus data"""
    ...
