"""
This type stub file was generated by pyright.
"""

def get_version(version=...):  # -> str:
    "Returns a PEP 440-compliant version number from VERSION."
    ...

def get_main_version(version=...):  # -> str:
    "Returns main version (X.Y[.Z]) from VERSION."
    ...

def get_complete_version(
    version=...,
):  # -> tuple[Literal[2], Literal[1], Literal[9], Literal['final'], Literal[0]]:
    """Returns a tuple of the graphene version. If version argument is non-empty,
    then checks for correctness of the tuple provided.
    """
    ...

def get_docs_version(version=...): ...
def get_git_changeset():  # -> str | None:
    """Returns a numeric identifier of the latest git changeset.
    The result is the UTC timestamp of the changeset in YYYYMMDDHHMMSS format.
    This value isn't guaranteed to be unique, but collisions are very unlikely,
    so it's sufficient for generating the development version numbers.
    """
    ...
