"""
This type stub file was generated by pyright.
"""

import warnings

from ..utils import DJANGO_FILTER_INSTALLED
from .fields import DjangoFilterConnectionField
from .filterset import GlobalIDFilter, GlobalIDMultipleChoiceFilter

if notDJANGO_FILTER_INSTALLED: ...
else: ...
