"""
This type stub file was generated by pyright.
"""

from ..fields import DjangoConnectionField

class DjangoFilterConnectionField(DjangoConnectionField):
    def __init__(
        self,
        type,
        fields=...,
        order_by=...,
        extra_filter_meta=...,
        filterset_class=...,
        *args,
        **kwargs
    ) -> None: ...
    @property
    def args(self): ...
    @args.setter
    def args(self, args): ...
    @property
    def filterset_class(self): ...
    @property
    def filtering_args(self): ...
    @classmethod
    def resolve_queryset(
        cls, connection, iterable, info, args, filtering_args, filterset_class
    ): ...
    def get_queryset_resolver(self): ...
