"""
This type stub file was generated by pyright.
"""

def get_filtering_args_from_filterset(
    filterset_class, type
):  # -> dict[Unknown, Unknown]:
    """Inspect a FilterSet and produce the arguments to pass to
    a Graphene Field. These arguments will be available to
    filter against in the GraphQL
    """
    ...

def get_filterset_class(filterset_class, **meta):  # -> Any | Type[_]:
    """
    Get the class to be used as the FilterSet.
    """
    ...

def replace_csv_filters(filterset_class):  # -> None:
    """
    Replace the "in" and "range" filters (that are not explicitly declared) to not be BaseCSVFilter (BaseInFilter, BaseRangeFilter) objects anymore
    but regular Filter objects that simply use the input value as filter argument on the queryset.

    This is because those BaseCSVFilter are expecting a string as input with comma separated value but with GraphQl we
    can actually have a list as input and have a proper type verification of each value in the list.

    See issue https://github.com/graphql-python/graphene-django/issues/1068.
    """
    ...
