friendly_name = "Default browser"
description = "Metrics that describe whether Fenix is a user's default browser."

[metrics.mozilla_default_browser]
friendly_name = "Has a Mozilla default browser"
description = """
    Fraction of users we observed during this analysis window who have a Mozilla default browser.
    The weekly view of this metric will tend to creep up over time and diverge from the overall view
    because we exclude users that we didn't observe at all, and users that do not have a Mozilla
    browser set as their default are more likely to churn.
"""
select_expression = """
    ARRAY_AGG(
        -- Limit the metric to clients who have actually been active during the analysis window.
        -- Otherwise, it's not clear what our denominator is.
        IF(metrics.counter.glean_validation_foreground_count > 0, metrics.string.metrics_default_moz_browser IS NOT NULL, NULL)
        IGNORE NULLS
        ORDER BY submission_timestamp DESC
        LIMIT 1
    )[SAFE_OFFSET(0)]
"""
data_source = "metrics"
statistics = { binomial = { pre_treatments = ["remove_nulls"] } }

[metrics.default_browser_action]
friendly_name = "Clicked to set Firefox as default"
description = """
    Fraction of users who clicked on a UI element to set Firefox as default
    during the analysis window.
    This only opens a system UI that allows users to change their default browser,
    so not all of these clients will actually change their default browser.
"""
select_expression = "COUNTIF(event.name = 'default_browser_changed') > 0"
data_source = "events"
statistics = { binomial = {} }
