"""
This type stub file was generated by pyright.
"""

logger = ...

def replicate(origin, destination):  # -> None:
    """Replicates records from one collection to another one.

    All records are replicated, not only the ones that changed.
    """
    ...

def get_arguments(): ...
def main(): ...

if __name__ == "__main__": ...
