"""
This type stub file was generated by pyright.
"""

def create_session(server_url=..., auth=..., session=..., **kwargs):  # -> Session:
    """Returns a session from the passed arguments.

    :param server_url:
        The URL of the server to use, with the prefix.
    :param auth:
        A requests authentication policy object.
    :param session:
        An optional session object to use, rather than creating a new one.
    """
    ...

class Session:
    """Handles all the interactions with the network."""

    def __init__(
        self, server_url, auth=..., timeout=..., headers=..., retry=..., retry_after=...
    ) -> None: ...
    def request(
        self, method, endpoint, data=..., permissions=..., payload=..., **kwargs
    ): ...
