"""
This type stub file was generated by pyright.
"""

def slugify(value):  # -> str:
    """Normalizes string, converts to lowercase, removes non-alpha characters
    and converts spaces to hyphens.
    """
    ...

def urljoin(server_url, path):
    """Return the url concatenation of server_url and path."""
    ...

def quote(text): ...
def chunks(lst, n):  # -> Generator[Unknown, None, None]:
    """Yield successive n-sized chunks from lst.
    Source: http://stackoverflow.com/a/312464
    """
    ...

def json_iso_datetime(obj):  # -> str:
    """JSON serializer for objects not serializable by default json code"""
    ...

json_dumps = ...
