# Generated by Django 3.0.4 on 2020-03-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("projects", "0004_delete_project")]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("name",),
            },
        )
    ]
