"""
This type stub file was generated by pyright.
"""

is_init_subclass_available = ...
if notis_init_subclass_available:
    class InitSubclassMeta(type):
        """Metaclass that implements PEP 487 protocol"""

        def __new__(cls, name, bases, ns, **kwargs): ...
        def __init__(cls, name, bases, ns, **kwargs) -> None: ...

else:
    InitSubclassMeta = ...
