"""
This type stub file was generated by pyright.
"""

import six
from graphene.types.schema import Schema
from graphql.error import GraphQLError
from graphql.error import format_error as format_graphql_error
from promise import Promise, is_thenable

def default_format_error(error): ...
def format_execution_result(execution_result, format_error): ...

class Client:
    def __init__(self, schema, format_error=..., **execute_options) -> None: ...
    def format_result(self, result): ...
    def execute(self, *args, **kwargs): ...
