[metrics]

[metrics.uri_count.statistics.bootstrap_mean]
[metrics.uri_count.statistics.deciles]


[metrics.user_reports_site_issue_count.statistics.bootstrap_mean]
[metrics.user_reports_site_issue_count.statistics.deciles]


[metrics.user_reload_count.statistics.bootstrap_mean]
[metrics.user_reload_count.statistics.deciles]


[metrics.baseline_ping_count.statistics.bootstrap_mean]
[metrics.baseline_ping_count.statistics.deciles]


[metrics.metric_ping_count.statistics.bootstrap_mean]
[metrics.metric_ping_count.statistics.deciles]


[metrics.first_run_date.statistics.count]


[metrics.active_hours.statistics.bootstrap_mean]
[metrics.active_hours.statistics.deciles]


[metrics.days_of_use.statistics.bootstrap_mean]
drop_highest = 0

[metrics.days_of_use.statistics.deciles]
[metrics.days_of_use.statistics.empirical_cdf]


[metrics.ad_clicks.statistics.bootstrap_mean]
[metrics.ad_clicks.statistics.deciles]


[metrics.tagged_sap_searches.statistics.bootstrap_mean]
[metrics.tagged_sap_searches.statistics.deciles]


[metrics.search_count.statistics.bootstrap_mean]
[metrics.search_count.statistics.deciles]

[metrics.turn_on_notifications_onboarding.statistics.binomial]
[metrics.set_to_default_onboarding.statistics.binomial]
[metrics.sign_in_onboarding.statistics.binomial]
[metrics.at_least_1_cta_onboarding.statistics.binomial]