[metrics]

[metrics.baseline_ping_count.statistics.bootstrap_mean]
[metrics.baseline_ping_count.statistics.deciles]


[metrics.metric_ping_count.statistics.bootstrap_mean]
[metrics.metric_ping_count.statistics.deciles]


[metrics.first_run_date.statistics.count]


[metrics.active_hours.statistics.bootstrap_mean]
[metrics.active_hours.statistics.deciles]


[metrics.days_of_use.statistics.bootstrap_mean]
drop_highest = 0

[metrics.days_of_use.statistics.deciles]
[metrics.days_of_use.statistics.empirical_cdf]


[metrics.ad_clicks.statistics.bootstrap_mean]
[metrics.ad_clicks.statistics.deciles]


[metrics.search_count.statistics.bootstrap_mean]
[metrics.search_count.statistics.deciles]
