# Generated by Django 3.2.5 on 2021-08-19 15:54

from django.db import migrations

MISSING_LOCALES = [
    ("bo", "Tibetan"),
    ("ckb", "Central Kurdish"),
    ("hye", "Armenian Eastern Classic Orthography"),
    ("meh", "Mixteco Yucuhiti"),
    ("scn", "Sicilian"),
    ("sco", "Scots"),
    ("szl", "Silesian"),
    ("tg", "Tajik"),
]


def add_locales(apps, schema_editor):
    Locale = apps.get_model("base", "Locale")
    for code, name in MISSING_LOCALES:
        Locale.objects.get_or_create(code=code, defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_non_firefox_locales"),
    ]

    operations = [
        migrations.RunPython(add_locales),
    ]
