# Generated by Django 5.2.2 on 2025-08-21 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_dismissed', models.BooleanField(default=False)),
                ('opt_out', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='glean_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'glean prefs',
                'verbose_name_plural': 'glean prefs',
            },
        ),
    ]
