# Generated by Django 5.2.8 on 2025-11-20 18:44

from django.db import migrations


def reset_dismiss_flag(apps, schema_editor):
    Prefs = apps.get_model("glean", "Prefs")
    Prefs.objects.update(alert_dismissed=False)

class Migration(migrations.Migration):

    dependencies = [
        ('glean', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(reset_dismiss_flag),
    ]
