# Generated by Django 5.2.9 on 2026-01-02 20:32

from uuid import uuid4

from django.db import migrations, models


def gen_nimbus_user_id(apps, schema_editor):
    Prefs = apps.get_model("glean", "Prefs")
    for row in Prefs.objects.all():
        if not row.opt_out:
            row.nimbus_user_id = uuid4()
            row.save(update_fields=["nimbus_user_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('glean', '0002_glean_dismiss_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefs',
            name='nimbus_user_id',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(gen_nimbus_user_id),
        migrations.AlterField(
            model_name='prefs',
            name='nimbus_user_id',
            field=models.UUIDField(default=uuid4, editable=False, null=True, unique=True),
        ),
    ]
