# Generated by Django 5.2.7 on 2025-10-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0294_alter_nimbusexperiment_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('change_date', models.DateTimeField()),
                ('change_size', models.CharField(blank=True, max_length=100, null=True)),
                ('complexity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='experiments.nimbusfeatureconfig')),
            ],
            options={
                'verbose_name': 'Feature Test Run',
                'verbose_name_plural': 'Feature Test Runs',
                'ordering': ['-change_date'],
                'indexes': [models.Index(fields=['feature_config', '-change_date'], name='features_fe_feature_312fc6_idx')],
            },
        ),
    ]
