"""
This type stub file was generated by pyright.
"""

from django.core.files.storage import Storage

class BaseStorage(Storage):
    def __init__(self, **settings) -> None: ...
    def get_default_settings(self): ...
