"""
This type stub file was generated by pyright.
"""

import io
from typing import Optional

class GzipCompressionWrapper(io.RawIOBase):
    """Wrapper for compressing file contents on the fly."""

    def __init__(self, raw, level=...) -> None: ...
    @staticmethod
    def readable(): ...
    def readinto(self, buf: bytearray) -> Optional[int]: ...

class CompressStorageMixin: ...
class CompressedFileMixin: ...
