"""
This type stub file was generated by pyright.
"""

from ..utils.subclass_with_meta import SubclassWithMeta

class AbstractType(SubclassWithMeta):
    def __init_subclass__(cls, *args, **kwargs): ...
