"""
This type stub file was generated by pyright.
"""

from .scalars import Scalar

class JSONString(Scalar):
    """
    Allows use of a JSON String for input / output from the GraphQL schema.

    Use of this type is *not recommended* as you lose the benefits of having a defined, static
    schema (one of the key benefits of GraphQL).
    """

    @staticmethod
    def serialize(dt): ...
    @staticmethod
    def parse_literal(node): ...
    @staticmethod
    def parse_value(value): ...
