"""
This type stub file was generated by pyright.
"""

def get_field_as(value, _as=...):  # -> MountedType | UnmountedType | None:
    """
    Get type mounted
    """
    ...

def yank_fields_from_attrs(attrs, _as=..., sort=...):  # -> OrderedDict[Unknown, Unknown]:
    """
    Extract all the fields in given attributes (dict)
    and return them ordered
    """
    ...

def get_type(_type): ...
