"""
This type stub file was generated by pyright.
"""

from kombu.utils.imports import symbol_by_name

"""Pool implementation abstract factory, and alias definitions."""
__all__ = ("get_implementation", "get_available_pool_names")
ALIASES = ...

def get_implementation(cls):  # -> Any | ModuleType:
    """Return pool implementation by name."""
    ...

def get_available_pool_names():  # -> tuple[str, ...]:
    """Return all available pool type names."""
    ...
