friendly_name = "Awesomebar Engagement Metrics"
description = "Metrics that describe user interactions with the Awesomebar."

[metrics.awesomebar_engagement]
friendly_name = "Awesomebar Engagement"
description = "Number of times a user completed their search session by tapping a search result, or entering a URL or a search term."
select_expression = """
    COALESCE(COUNTIF(event_name = 'engagement'), 0)
"""
data_source = "events_stream_awesomebar"
statistics = { sum = {}, bootstrap_mean = {}, deciles = {} }

[metrics.awesomebar_abandonment]
friendly_name = "Awesomebar Abandonment"
description = "Number of times a user dismissed the awesomebar without completing their search."
select_expression = """
    COALESCE(COUNTIF(event_name = 'abandonment'), 0)
"""
data_source = "events_stream_awesomebar"
statistics = { sum = {}, bootstrap_mean = {}, deciles = {} }
