friendly_name = "Onboarding"
description = "Metrics relevant to onboarding (default browser rate)"


[metrics.turn_on_notifications_onboarding.statistics.binomial]
[metrics.set_to_default_onboarding.statistics.binomial]
[metrics.sign_in_onboarding.statistics.binomial]
[metrics.at_least_1_cta_onboarding.statistics.binomial]