"""
This type stub file was generated by pyright.
"""

from faker.factory import Factory
from faker.generator import Generator
from faker.proxy import Faker

VERSION = ...
__all__ = ("Factory", "Generator", "Faker")
