"""
This type stub file was generated by pyright.
"""

string_types = ...

def warn_deprecation(text): ...
def deprecated(
    reason,
):  # -> ((func1: Unknown) -> ((*args: Unknown, **kwargs: Unknown) -> (Any | Unknown))) | ((*args: Unknown, **kwargs: Unknown) -> Any):
    """
    This is a decorator which can be used to mark functions
    as deprecated. It will result in a warning being emitted
    when the function is used.
    """
    ...
