"""
This type stub file was generated by pyright.
"""

"""
This file is used mainly as a bridge for thenable abstractions.
This includes:
- Promises
- Asyncio Coroutines
"""

def maybe_thenable(obj, on_resolve):  # -> Coroutine[Any, Any, Unknown]:
    """
    Execute a on_resolve function once the thenable is resolved,
    returning the same type of object inputed.
    If the object is not thenable, it should return on_resolve(obj)
    """
    ...
