"""
This type stub file was generated by pyright.
"""

import six

from ..pyutils.init_subclass import InitSubclassMeta

class SubclassWithMeta_Meta(InitSubclassMeta):
    _meta = ...
    def __str__(cls) -> str: ...
    def __repr__(cls): ...

class SubclassWithMeta(six.with_metaclass(SubclassWithMeta_Meta)):
    """This class improves __init_subclass__ to receive automatically the options from meta"""

    def __init_subclass__(cls, **meta_options):  # -> None:
        """This method just terminates the super() chain"""
        ...
    @classmethod
    def __init_subclass_with_meta__(cls, **meta_options):  # -> None:
        """This method just terminates the super() chain"""
        ...
