# Generated by Django 3.1.8 on 2021-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0005_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("experiment_slug", models.CharField(max_length=255)),
                ("experiment_name", models.CharField(max_length=255)),
                (
                    "experiment_type",
                    models.CharField(
                        choices=[
                            ("Normandy Pref", "Normandy Pref"),
                            ("Normandy Addon", "Normandy Addon"),
                            ("Normandy Rollout", "Normandy Rollout"),
                            ("Nimbus Desktop", "Nimbus Desktop"),
                            ("Nimbus Fenix", "Nimbus Fenix"),
                            ("Nimbus IOS", "Nimbus Ios"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "experiment_old_status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Preview", "Preview"),
                            ("Review", "Review"),
                            ("Ship", "Ship"),
                            ("Accepted", "Accepted"),
                            ("Live", "Live"),
                            ("Complete", "Complete"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "experiment_new_status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Preview", "Preview"),
                            ("Review", "Review"),
                            ("Ship", "Ship"),
                            ("Accepted", "Accepted"),
                            ("Live", "Live"),
                            ("Complete", "Complete"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("Create", "Create"),
                            ("Update", "Update"),
                            ("End", "End"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "event_reason",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Clone", "Clone"),
                            ("Relaunch", "Relaunch"),
                            ("Status Change", "Status Change"),
                            ("Pause", "Pause"),
                            ("Recipe Change", "Recipe Change"),
                            ("QA Launch", "Qa Launch"),
                            ("Launch", "Launch"),
                            ("Experiment Complete", "Experiment Complete"),
                            ("Filtering Issue", "Filtering Issue"),
                            ("Enrollment Issue", "Enrollment Issue"),
                            ("Experiment Design Issue", "Experiment Design Issue"),
                            ("Results Added", "Results Added"),
                        ],
                        max_length=255,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("projects", models.ManyToManyField(blank=True, to="projects.Project")),
            ],
            options={
                "verbose_name": "ReportLog",
                "verbose_name_plural": "ReportLogs",
                "ordering": ("timestamp",),
            },
        ),
    ]
