# Generated by Django 3.1.8 on 2021-05-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportlog",
            name="experiment_old_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Draft", "Draft"),
                    ("Preview", "Preview"),
                    ("Review", "Review"),
                    ("Ship", "Ship"),
                    ("Accepted", "Accepted"),
                    ("Live", "Live"),
                    ("Complete", "Complete"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
