# Generated by Django 3.2.12 on 2022-04-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0004_alter_reportlog_experiment_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportLog",
        ),
    ]
