"""
This type stub file was generated by pyright.
"""

from django_filters import filterset

FILTER_FOR_DBFIELD_DEFAULTS = ...

class FilterSet(filterset.FilterSet):
    FILTER_DEFAULTS = ...
    @property
    def form(self): ...
