"""
This type stub file was generated by pyright.
"""

from typing import Type

import six
from django.db.models import Model
from graphene.relay import Connection
from graphene.types.objecttype import ObjectType, ObjectTypeOptions

from .registry import Registry

if six.PY3: ...
ALL_FIELDS = ...

def construct_fields(
    model, registry, only_fields, exclude_fields, convert_choices_to_enum
): ...
def validate_fields(type_, model, fields, only_fields, exclude_fields): ...

class DjangoObjectTypeOptions(ObjectTypeOptions):
    model: Model = ...
    registry: Registry = ...
    connection: Type[Connection] = ...
    filter_fields = ...
    filterset_class = ...

class DjangoObjectType(ObjectType):
    @classmethod
    def __init_subclass_with_meta__(
        cls,
        model=...,
        registry=...,
        skip_registry=...,
        only_fields=...,
        fields=...,
        exclude_fields=...,
        exclude=...,
        filter_fields=...,
        filterset_class=...,
        connection=...,
        connection_class=...,
        use_connection=...,
        interfaces=...,
        convert_choices_to_enum=...,
        _meta=...,
        **options
    ): ...
    def resolve_id(self, info): ...
    @classmethod
    def is_type_of(cls, root, info): ...
    @classmethod
    def get_queryset(cls, queryset, info): ...
    @classmethod
    def get_node(cls, info, id): ...

class ErrorType(ObjectType):
    field = ...
    messages = ...
    @classmethod
    def from_errors(cls, errors): ...
