FROM python:3.11-buster

COPY --from=as-builder /application-services/nimbus-experimenter /application-services
ENV PYTHON_PATH=$PYTHON_PATH:/application-services/megazord

RUN apt-get update -qqy \
  && apt-get -qqy install \
    tox

WORKDIR /code
