"""
This type stub file was generated by pyright.
"""

from . import base

SESSION_PERSISTENCE_COMMIT = ...
SESSION_PERSISTENCE_FLUSH = ...
VALID_SESSION_PERSISTENCE_TYPES = ...

class SQLAlchemyOptions(base.FactoryOptions): ...

class SQLAlchemyModelFactory(base.Factory):
    """Factory for SQLAlchemy models."""

    _options_class = SQLAlchemyOptions

    class Meta:
        abstract = ...
