"""
This type stub file was generated by pyright.
"""

from . import base

"""factory_boy extensions for use with the mogo library (pymongo wrapper)."""

class MogoFactory(base.Factory):
    """Factory for mogo objects."""

    class Meta:
        abstract = ...
