"""
This type stub file was generated by pyright.
"""

from . import base

"""factory_boy extensions for use with the mongoengine library (pymongo wrapper)."""

class MongoEngineFactory(base.Factory):
    """Factory for mongoengine objects."""

    class Meta:
        abstract = ...
