"""
This type stub file was generated by pyright.
"""

from typing import Any

from django.db import models

class Token(models.Model):
    key: models.CharField[Any] = ...
    user: models.OneToOneField[Any] = ...
    created: models.DateTimeField[Any] = ...
    @classmethod
    def generate_key(cls) -> str: ...

class TokenProxy(Token):
    @property
    def pk(self) -> Any: ...
