"""
This type stub file was generated by pyright.
"""

import builtins
import os
import re
import sys
from collections import namedtuple

from celery._state import current_app, current_task
from celery.app import shared_task
from celery.app.base import Celery
from celery.app.task import Task
from celery.app.utils import bugreport
from celery.canvas import (
    chain,
    chord,
    chunks,
    group,
    maybe_signature,
    signature,
    subtask,
    xmap,
    xstarmap,
)
from celery.utils import uuid

from . import local

"""Distributed Task Queue."""
SERIES = ...
__version__ = ...
__author__ = ...
__contact__ = ...
__homepage__ = ...
__docformat__ = ...
__keywords__ = ...
__all__ = (
    "Celery",
    "bugreport",
    "shared_task",
    "Task",
    "current_app",
    "current_task",
    "maybe_signature",
    "chain",
    "chord",
    "chunks",
    "group",
    "signature",
    "xmap",
    "xstarmap",
    "uuid",
)
VERSION_BANNER = ...
version_info_t = ...
_temp = ...
VERSION = ...
if os.environ.get("C_IMPDEBUG"):
    def debug_import(
        name, locals=..., globals=..., fromlist=..., level=..., real_import=...
    ): ...

STATICA_HACK = ...
if STATICA_HACK: ...

def maybe_patch_concurrency(
    argv=..., short_opts=..., long_opts=..., patches=...
):  # -> None:
    """Apply eventlet/gevent monkeypatches.

    With short and long opt alternatives that specify the command line
    option to set the pool, this makes sure that anything that needs
    to be patched is completed as early as possible.
    (e.g., eventlet/gevent monkey patches).
    """
    ...
