"""
This type stub file was generated by pyright.
"""

import contextlib

from . import declarations

"""Additional declarations for "faker" attributes.

Usage:

    class MyFactory(factory.Factory):
        class Meta:
            model = MyProfile

        first_name = factory.Faker('name')
"""

class Faker(declarations.BaseDeclaration):
    """Wrapper for 'faker' values.

    Args:
        provider (str): the name of the Faker field
        locale (str): the locale to use for the faker

        All other kwargs will be passed to the underlying provider
        (e.g ``factory.Faker('ean', length=10)``
        calls ``faker.Faker.ean(length=10)``)

    Usage:
        >>> foo = factory.Faker('name')
    """

    def __init__(self, provider, **kwargs) -> None: ...
    def evaluate(self, instance, step, extra): ...
    _FAKER_REGISTRY = ...
    _DEFAULT_LOCALE = ...
    @classmethod
    @contextlib.contextmanager
    def override_default_locale(cls, locale): ...
    @classmethod
    def add_provider(cls, provider, locale=...):  # -> None:
        """Add a new Faker provider for the specified locale"""
        ...
