"""
This type stub file was generated by pyright.
"""

randgen = ...

def get_random_state():  # -> tuple[Any, ...]:
    """Retrieve the state of factory.fuzzy's random generator."""
    ...

def set_random_state(state):  # -> None:
    """Force-set the state of factory.fuzzy's random generator."""
    ...

def reseed_random(seed):  # -> None:
    """Reseed factory.fuzzy's random generator."""
    ...
