friendly_name = "Pocket metrics"
description = "Metrics that describe Pocket usage"

[metrics.pocket_section_impressions]
friendly_name = "Pocket Impressions"
description = "Number of times Pocket content is shown on the home screen."
select_expression = """
      COALESCE(SUM(
          metrics.counter.pocket_section_impressions
      ),0)
"""
data_source = "metrics"  
statistics = { bootstrap_mean = {}, deciles = {} } 


[metrics.pocket_story_clicks]
friendly_name = "Pocket Story Clicks"
description = "Number of times user clicked on a Pocket story."
select_expression = """
      SUM(COALESCE(`mozfun.map.get_key`(metrics.labeled_counter.pocket_open_story_origin, 'zero-search'),0) + 
		COALESCE(`mozfun.map.get_key`(metrics.labeled_counter.pocket_open_story_origin, 'origin-other'),0))
"""
data_source = "metrics" 
statistics = { bootstrap_mean = {}, deciles = {} }
