friendly_name = "Sponsored Tiles"
description = "Metrics that describe Sponsored Tiles usage"


[metrics.spoc_tiles_impressions]
friendly_name = "Sponsored Tiles Impressions"
description = "Number of times Contile Sponsored Tiles are shown."
select_expression = """
      COALESCE(COUNTIF(
          event.category = 'top_site'
          AND event.name = 'contile_impression'
      ),0)
"""
data_source = "events"   
statistics = { bootstrap_mean = {}, deciles = {} }


[metrics.spoc_tiles_clicks]
friendly_name = "Sponsored Tiles Clicks"
description = "Number of times user clicked a Contile Sponsored Tile."
select_expression = """
      COALESCE(COUNTIF(
          event.category = 'top_site'
          AND event.name = 'contile_click'
      ),0)
"""
data_source = "events" 
statistics = { bootstrap_mean = {}, deciles = {} }


[metrics.spoc_tiles_preference_toggled]
select_expression = """   
  COALESCE(SUM(CASE WHEN
          event.category = 'preferences'
          AND event.name = 'changed'
          AND `mozfun.map.get_key`(event.extra, 'preference') = 'sponsoredTiles'
	THEN 1 ELSE 0 END
  ),0)
"""
data_source = "events" 
bigger_is_better = false
friendly_name = "Sponsored Tiles Preference Toggled"
description = "Number of times Contile Sponsored Tiles setting is flipped."
statistics = { bootstrap_mean = {}, deciles = {} } 