---
site_name: Jetstream Config
site_description: Configurations for Experiments
site_author: Mozilla Data Platform Team

# Repository
repo_name: mozilla/jetstream-config
repo_url: https://github.com/mozilla/jetstream-config/
edit_uri: ""

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: teal
  favicon: favicon.png
  custom_dir: overrides

plugins:
  - search
  - awesome-pages
nav:
  - index.md
  - Outcomes:
      - ... | outcomes/**/**.md
  - Metrics:
      - ... | metrics/**.md
  - Data Sources:
      - ... | data_sources/**.md
  - Default Configs:
      - ... | default_configs/**.md
