"""
This type stub file was generated by pyright.
"""

class ImportExportError(Exception):
    """A generic exception for all others to extend."""

    ...

class FieldError(ImportExportError):
    """Raised when a field encounters an error."""

    ...
