"""
This type stub file was generated by pyright.
"""

from django.views.generic.edit import FormView

from .forms import ExportForm

class BaseImportExportMixin:
    formats = ...
    resource_class = ...
    def get_resource_class(self): ...
    def get_resource_kwargs(self, request, *args, **kwargs): ...

class BaseImportMixin(BaseImportExportMixin):
    def get_import_resource_class(self):  # -> Type[__class_ModelDeclarativeMetaclass]:
        """
        Returns ResourceClass to use for import.
        """
        ...
    def get_import_formats(
        self,
    ):  # -> list[Type[CSV] | Type[XLS] | Type[XLSX] | Type[TSV] | Type[ODS] | Type[JSON] | Type[YAML] | Type[HTML]]:
        """
        Returns available import formats.
        """
        ...
    def get_import_resource_kwargs(self, request, *args, **kwargs): ...

class BaseExportMixin(BaseImportExportMixin):
    model = ...
    def get_export_formats(
        self,
    ):  # -> list[Type[CSV] | Type[XLS] | Type[XLSX] | Type[TSV] | Type[ODS] | Type[JSON] | Type[YAML] | Type[HTML]]:
        """
        Returns available export formats.
        """
        ...
    def get_export_resource_class(self):  # -> Type[__class_ModelDeclarativeMetaclass]:
        """
        Returns ResourceClass to use for export.
        """
        ...
    def get_export_resource_kwargs(self, request, *args, **kwargs): ...
    def get_data_for_export(self, request, queryset, *args, **kwargs): ...
    def get_export_filename(self, file_format): ...

class ExportViewMixin(BaseExportMixin):
    form_class = ExportForm
    def get_export_data(self, file_format, queryset, *args, **kwargs):
        """
        Returns file_format representation for given queryset.
        """
        ...
    def get_context_data(self, **kwargs): ...
    def get_form_kwargs(self): ...

class ExportViewFormMixin(ExportViewMixin, FormView):
    def form_valid(self, form): ...
