"""
This type stub file was generated by pyright.
"""

class Operator:
    __slots__ = ...
    def __init__(self, symbol, precedence, evaluate, evaluate_lazy=...) -> None:
        """Operator definition.

        If evaluate_lazy is set to True, the `evaluate()` method will receive
        it's parameters as a lambda expression that needs to be called to
        receive the value of the expression. Otherwise, the values will
        already be evaluated.
        """
        ...
    def do_evaluate(self, *args): ...
    def __repr__(self): ...

default_binary_operators = ...
default_unary_operators = ...
