[metrics]
daily = ["was_ever_default_browser", "was_never_default_browser"]
weekly = ["was_ever_default_browser", "was_never_default_browser"]
overall = ["was_ever_default_browser", "was_never_default_browser"]

[metrics.was_ever_default_browser]
select_expression = "LOGICAL_OR(is_default_browser)"
data_source = "clients_daily"

[metrics.was_ever_default_browser.statistics.binomial]
pre_treatments = ["remove_nulls"]

[metrics.was_never_default_browser]
select_expression = "LOGICAL_AND(NOT is_default_browser)"
data_source = "clients_daily"

[metrics.was_never_default_browser.statistics.binomial]
pre_treatments = ["remove_nulls"]
