[experiment]
segments = [
    'low_cpu', 'med_cpu', 'high_cpu',
    'low_mem', 'med_mem', 'high_mem',
    'regular_users_v3', 'new_or_resurrected_v3'
]

[metrics]
overall = [
    'perf_page_load_time_ms', 'perf_page_load_time_from_responsestart_ms',
    'perf_dom_content_loaded_time_ms', 'perf_dom_content_loaded_time_from_responsestart_ms',
    'perf_first_contentful_paint_ms', 'perf_first_contentful_paint_from_responsestart_ms',
    'perf_request_animation_callback_pageload_ms', 'perf_request_animation_callback_non_pageload_ms',
    'js_execution_proportion',
    'time_to_first_interaction_ms', 'input_event_response_ms',
    'content_keypress_present_latency', 'gpu_keypress_present_latency',
    'load_input_event_response_ms', 'load_input_event_response_no_preload_ms', 'load_input_event_response_preload_ms',
    'about_home_topsites_first_paint',
    'fx_new_window_ms'
]
    [metrics.perf_page_load_time_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.perf_page_load_time_ms")}}'
    data_source = 'main'

        [metrics.perf_page_load_time_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_page_load_time_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_page_load_time_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.perf_page_load_time_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.perf_page_load_time_from_responsestart_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.perf_page_load_time_from_responsestart_ms")}}'
    data_source = 'main'

        [metrics.perf_page_load_time_from_responsestart_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_page_load_time_from_responsestart_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_page_load_time_from_responsestart_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.perf_page_load_time_from_responsestart_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.perf_dom_content_loaded_time_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.perf_dom_content_loaded_time_ms")}}'
    data_source = 'main'

        [metrics.perf_dom_content_loaded_time_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_dom_content_loaded_time_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_dom_content_loaded_time_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.perf_dom_content_loaded_time_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.perf_dom_content_loaded_time_from_responsestart_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.perf_dom_content_loaded_time_from_responsestart_ms")}}'
    data_source = 'main'

        [metrics.perf_dom_content_loaded_time_from_responsestart_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_dom_content_loaded_time_from_responsestart_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_dom_content_loaded_time_from_responsestart_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.perf_dom_content_loaded_time_from_responsestart_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.perf_first_contentful_paint_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.perf_first_contentful_paint_ms")}}'
    data_source = 'main'

        [metrics.perf_first_contentful_paint_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_first_contentful_paint_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_first_contentful_paint_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.perf_first_contentful_paint_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.perf_first_contentful_paint_from_responsestart_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.perf_first_contentful_paint_from_responsestart_ms")}}'
    data_source = 'main'

        [metrics.perf_first_contentful_paint_from_responsestart_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_first_contentful_paint_from_responsestart_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_first_contentful_paint_from_responsestart_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.perf_first_contentful_paint_from_responsestart_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.perf_request_animation_callback_pageload_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.perf_request_animation_callback_pageload_ms")}}'
    data_source = 'main'

        [metrics.perf_request_animation_callback_pageload_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_request_animation_callback_pageload_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_request_animation_callback_pageload_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.perf_request_animation_callback_pageload_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.perf_request_animation_callback_non_pageload_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.perf_request_animation_callback_non_pageload_ms")}}'
    data_source = 'main'

        [metrics.perf_request_animation_callback_non_pageload_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_request_animation_callback_non_pageload_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.perf_request_animation_callback_non_pageload_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.perf_request_animation_callback_non_pageload_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.js_execution_proportion]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.js_execution_proportion")}}'
    data_source = 'main'

        [metrics.js_execution_proportion.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.js_execution_proportion.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.js_execution_proportion.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.js_execution_proportion.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.time_to_first_interaction_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.time_to_first_interaction_ms")}}'
    data_source = 'main'

        [metrics.time_to_first_interaction_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.time_to_first_interaction_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.time_to_first_interaction_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.time_to_first_interaction_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.input_event_response_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.input_event_response_ms")}}'
    data_source = 'main'

        [metrics.input_event_response_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.input_event_response_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.input_event_response_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.input_event_response_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.content_keypress_present_latency]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.keypress_present_latency")}}'
    data_source = 'main'

        [metrics.content_keypress_present_latency.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.content_keypress_present_latency.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.content_keypress_present_latency.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.content_keypress_present_latency.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.gpu_keypress_present_latency]
    select_expression = '{{agg_histogram_mean("payload.processes.gpu.histograms.keypress_present_latency")}}'
    data_source = 'main'

        [metrics.gpu_keypress_present_latency.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.gpu_keypress_present_latency.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.gpu_keypress_present_latency.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.gpu_keypress_present_latency.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.load_input_event_response_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.load_input_event_response_ms")}}'
    data_source = 'main'

        [metrics.load_input_event_response_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.load_input_event_response_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.load_input_event_response_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.load_input_event_response_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.load_input_event_response_no_preload_ms]
    select_expression = '{{agg_histogram_mean("payload.histograms.load_input_event_response_no_preload_ms")}}'
    data_source = 'main'

        [metrics.load_input_event_response_no_preload_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.load_input_event_response_no_preload_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.load_input_event_response_no_preload_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.load_input_event_response_no_preload_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.load_input_event_response_preload_ms]
    select_expression = '{{agg_histogram_mean("payload.histograms.load_input_event_response_preload_ms")}}'
    data_source = 'main'

        [metrics.load_input_event_response_preload_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.load_input_event_response_preload_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.load_input_event_response_preload_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.load_input_event_response_preload_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.about_home_topsites_first_paint]
    select_expression = 'SUM(COALESCE(payload.processes.parent.scalars.timestamps_about_home_topsites_first_paint))'
    data_source = 'main'

        [metrics.about_home_topsites_first_paint.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.about_home_topsites_first_paint.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.about_home_topsites_first_paint.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.about_home_topsites_first_paint.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true

    [metrics.fx_new_window_ms]
    select_expression = '{{agg_histogram_mean("payload.processes.content.histograms.fx_new_window_ms")}}'
    data_source = 'main'

        [metrics.fx_new_window_ms.statistics.bootstrap_mean]
        pre_treatments = ["remove_nulls"]

        [metrics.fx_new_window_ms.statistics.deciles]
        pre_treatments = ["remove_nulls"]

        [metrics.fx_new_window_ms.statistics.kernel_density_estimate]
        pre_treatments = ["remove_nulls"]
        log_space = true

        [metrics.fx_new_window_ms.statistics.empirical_cdf]
        pre_treatments = ["remove_nulls"]
        log_space = true



## Segments

[segments.low_cpu]
select_expression = 'COALESCE(MAX(cpu_count) BETWEEN 1 AND 2, FALSE)'
data_source = "clients_last_seen"

[segments.med_cpu]
select_expression = 'COALESCE(MAX(cpu_count) BETWEEN 3 AND 5, FALSE)'
data_source = "clients_last_seen"

[segments.high_cpu]
select_expression = 'COALESCE(MAX(cpu_count) >= 6, FALSE)'
data_source = "clients_last_seen"

[segments.low_mem]
select_expression = 'COALESCE(MAX(memory_mb) BETWEEN 1 AND 4095, FALSE)'
data_source = "clients_last_seen"

[segments.med_mem]
select_expression = 'COALESCE(MAX(memory_mb) BETWEEN 4096 AND 8191, FALSE)'
data_source = "clients_last_seen"

[segments.high_mem]
select_expression = 'COALESCE(MAX(memory_mb) >= 8192, FALSE)'
data_source = "clients_last_seen"