# https://experimenter.services.mozilla.com/experiments/pre-xul-skeleton-ui-startup-improvement-experiment-new-users/
# Targets new users

[experiment]
segments = ["low_cpu", "better_cpu", "hdd", "ssd"]

[segments.low_cpu]
select_expression = 'COALESCE(MAX(cpu_count) BETWEEN 1 AND 2, FALSE)'
data_source = "clients_last_seen"

[segments.better_cpu]
select_expression = 'NOT COALESCE(MAX(cpu_count) BETWEEN 1 AND 2, FALSE)'
data_source = "clients_last_seen"

[segments.hdd]
select_expression = "COALESCE(ANY_VALUE(hdd_type) = 'HDD', FALSE)"
data_source = "events"

[segments.ssd]
select_expression = "COALESCE(ANY_VALUE(hdd_type) = 'SSD', FALSE)"
data_source = "events"

[segments.data_sources.events]
from_expression = """
    (SELECT
        DATE(submission_timestamp) AS submission_date,
        client_id,
        environment.system.hdd.profile.type AS hdd_type,
    FROM `moz-fx-data-shared-prod`.telemetry.event)
    """

