# https://experimenter.services.mozilla.com/experiments/pre-xul-skeleton-ui-and-abouthome-startup-cache-startup-improvement-experiment/
# Targets existing users

[experiment]
segments = ["low_cpu", "better_cpu", "hdd", "ssd"]

[segments.low_cpu]
select_expression = 'COALESCE(MAX(cpu_count) BETWEEN 1 AND 2, FALSE)'
data_source = "clients_last_seen"

[segments.better_cpu]
select_expression = 'NOT COALESCE(MAX(cpu_count) BETWEEN 1 AND 2, FALSE)'
data_source = "clients_last_seen"

[segments.hdd]
select_expression = "COALESCE(ANY_VALUE(hdd_type) = 'HDD', FALSE)"
data_source = "events"

[segments.ssd]
select_expression = "COALESCE(ANY_VALUE(hdd_type) = 'SSD', FALSE)"
data_source = "events"

[segments.data_sources.events]
from_expression = """
    (SELECT
        DATE(submission_timestamp) AS submission_date,
        client_id,
        environment.system.hdd.profile.type AS hdd_type,
    FROM `moz-fx-data-shared-prod`.telemetry.event)
    """

##

[metrics.active_hours.statistics.bootstrap_mean]
drop_highest = 0.01
[metrics.active_hours.statistics.deciles]

[metrics.ad_clicks.statistics.bootstrap_mean]
drop_highest = 0.01
[metrics.ad_clicks.statistics.deciles]

[metrics.organic_search_count.statistics.bootstrap_mean]
drop_highest = 0.01
[metrics.organic_search_count.statistics.deciles]

[metrics.uri_count.statistics.bootstrap_mean]
drop_highest = 0.01
[metrics.uri_count.statistics.deciles]

[metrics.search_count.statistics.bootstrap_mean]
drop_highest = 0.01
[metrics.search_count.statistics.deciles]

[metrics.searches_with_ads.statistics.bootstrap_mean]
drop_highest = 0.01
[metrics.searches_with_ads.statistics.deciles]

[metrics.tagged_search_count.statistics.bootstrap_mean]
drop_highest = 0.01
[metrics.tagged_search_count.statistics.deciles]

[metrics.tagged_follow_on_search_count.statistics.bootstrap_mean]
drop_highest = 0.01
[metrics.tagged_follow_on_search_count.statistics.deciles]
