[experiment]
segments = ['urlbar_users', 'searchsuggestion_users']

[segments.urlbar_users]
select_expression = 'COALESCE(LOGICAL_OR((events.key like "urlbar#%#%") AND (events.value > 0)), FALSE)'
data_source = "clients_daily_unnested"

[segments.data_sources.clients_daily_unnested]
from_expression = """(
  SELECT 
    submission_date,
    client_id,
    events
  FROM
    `moz-fx-data-shared-prod`.telemetry.clients_daily
  CROSS JOIN
    UNNEST(scalar_parent_telemetry_event_counts_sum) AS events
)"""
window_start = -7
window_end = 0

[segments.searchsuggestion_users]
select_expression = """
  COALESCE((SUM(COALESCE((
    SELECT SUM(x.value) FROM UNNEST(scalar_parent_urlbar_picked_searchsuggestion_sum
  ) x), 0)) > 0), FALSE)
"""
data_source = "clients_daily_custom_windows"

[segments.data_sources.clients_daily_custom_windows]
from_expression = "mozdata.telemetry.clients_daily"
window_start = -7
window_end = 0

