[experiment]

[data_sources.events_unnested]
from_expression = """(
  SELECT
    *
  FROM
    `moz-fx-data-shared-prod.telemetry.events`
)"""

[experiment.exposure_signal]
name = "nimbus_exposure"
friendly_name = "Nimbus Exposure"
description = "Firefox Suggest exposure per analysis window"
select_expression = """
    event_category = 'normandy'
    AND event_method = 'expose'
    AND event_object = 'nimbus_experiment'
    AND event_string_value = 'firefox-suggest-by-merino-beta'
    AND normalized_channel = 'beta'
    AND country = 'US'
"""
data_source = "events_unnested"
window_start = "analysis_window_start"
window_end = "analysis_window_end"

[metrics]
weekly = ["merino_latency", "remote_settings_latency", "merino_success", "merino_timeout", "merino_network_error", "merino_http_error"]
overall = ["merino_latency", "remote_settings_latency", "merino_success", "merino_timeout", "merino_network_error", "merino_http_error"]

[metrics.merino_latency]
select_expression = """
  SAFE_DIVIDE(
    SUM(COALESCE(`moz-fx-data-shared-prod.udf.json_extract_histogram`(
      payload.histograms.fx_urlbar_merino_latency_ms
    ).sum, 0)), 
    SUM(COALESCE(`moz-fx-data-shared-prod.udf.histogram_to_threshold_count`(
      payload.histograms.fx_urlbar_merino_latency_ms
    , -1), 0))
  )
"""
data_source = "main"
friendly_name = "Merino Latency"
description = "Average Merino latency per user"
analysis_bases = ["exposures", "enrollments"]
[metrics.merino_latency.statistics.bootstrap_mean]

[metrics.remote_settings_latency]
select_expression = """
  SAFE_DIVIDE(
    SUM(COALESCE(`moz-fx-data-shared-prod.udf.json_extract_histogram`(
      payload.histograms.fx_urlbar_quick_suggest_remote_settings_latency_ms
    ).sum, 0)), 
    SUM(COALESCE(`moz-fx-data-shared-prod.udf.histogram_to_threshold_count`(
      payload.histograms.fx_urlbar_quick_suggest_remote_settings_latency_ms
    , -1), 0))
  )
"""
data_source = "main"
friendly_name = "Remote Settings Latency"
description = "Average Remote Settings latency per user"
analysis_bases = ["exposures", "enrollments"]
[metrics.remote_settings_latency.statistics.bootstrap_mean]

[metrics.merino_success]
select_expression = """
  SUM(COALESCE(`moz-fx-data-shared-prod.udf.get_key`(`moz-fx-data-shared-prod.udf.json_extract_histogram`(
    payload.histograms.FX_URLBAR_MERINO_RESPONSE
  ).values, 0),0))
"""
data_source = "main"
friendly_name = "Merino Response: Success"
description = "Average number of Merino responses that returned `success` per user"
analysis_bases = ["exposures", "enrollments"]
[metrics.merino_success.statistics.bootstrap_mean]

[metrics.merino_timeout]
select_expression = """
  SUM(COALESCE(`moz-fx-data-shared-prod.udf.get_key`(`moz-fx-data-shared-prod.udf.json_extract_histogram`(
    payload.histograms.FX_URLBAR_MERINO_RESPONSE
  ).values, 1),0))
"""
data_source = "main"
friendly_name = "Merino Response: Timeout"
description = "Average number of Merino responses that returned `timeout` per user"
analysis_bases = ["exposures", "enrollments"]
[metrics.merino_timeout.statistics.bootstrap_mean]

[metrics.merino_network_error]
select_expression = """
  SUM(COALESCE(`moz-fx-data-shared-prod.udf.get_key`(`moz-fx-data-shared-prod.udf.json_extract_histogram`(
    payload.histograms.FX_URLBAR_MERINO_RESPONSE
  ).values, 2),0))
"""
data_source = "main"
friendly_name = "Merino Response: Network Error"
description = "Average number of Merino responses that returned `network error` per user"
analysis_bases = ["exposures", "enrollments"]
[metrics.merino_network_error.statistics.bootstrap_mean]

[metrics.merino_http_error]
select_expression = """
  SUM(COALESCE(`moz-fx-data-shared-prod.udf.get_key`(`moz-fx-data-shared-prod.udf.json_extract_histogram`(
    payload.histograms.FX_URLBAR_MERINO_RESPONSE
  ).values, 3),0))
"""
data_source = "main"
friendly_name = "Merino Response: HTTP Error"
description = "Average number of Merino responses that returned `HTTP Error` per user"
analysis_bases = ["exposures", "enrollments"]
[metrics.merino_http_error.statistics.bootstrap_mean]
