[experiment]
start_date = "2021-08-17"
end_date = "2021-09-14"
enrollment_period = 7
segments = ["regular_users_v3", "new_or_resurrected_v3", "is_core_active_v1", "is_casual_or_infrequent"]

[segments.is_core_active_v1]
select_expression = '{{agg_any("is_core_active_v1")}}'
data_source = "clients_last_seen"

[segments.is_casual_or_infrequent]
select_expression = 'COALESCE(LOGICAL_OR(BIT_COUNT(days_seen_bits) < 14), FALSE)'
data_source = "clients_last_seen"

[metrics]
overall = ["was_ever_default_browser", "was_never_default_browser"]

[metrics.was_ever_default_browser]
select_expression = "LOGICAL_OR(is_default_browser)"
data_source = "clients_daily"

[metrics.was_ever_default_browser.statistics.binomial]
pre_treatments = ["remove_nulls"]

[metrics.was_never_default_browser]
select_expression = "LOGICAL_OR(NOT is_default_browser)"
data_source = "clients_daily"

[metrics.was_never_default_browser.statistics.binomial]
pre_treatments = ["remove_nulls"]
