[experiment]

segments = ["attributed", "non_attributed"]

enrollment_period = 7

reference_branch = "control"

## Segments

[segments]

[segments.attributed]
select_expression = 'max(attr_source is not null)'
data_source = "npp"

[segments.non_attributed]
select_expression = 'max(attr_source is null)'
data_source = "npp"

[segments.data_sources.npp]
from_expression = """
    (SELECT
        DATE(submission_timestamp) AS submission_date,
        client_id,
        environment.settings.attribution.source AS attr_source
    FROM `moz-fx-data-shared-prod.telemetry.new_profile`
    WHERE environment.partner.distribution_id IS NULL
    AND coalesce(environment.settings.attribution.ua, '') != 'firefox'
    )
    """
window_start = -2
window_end = 0

## Metrics

[metrics]

weekly = ['days_of_use', 'search_count', 'organic_search_count', 'active_hours', 'unenroll',
    'set_to_default_rate']

overall = ['days_of_use', 'search_count', 'organic_search_count', 'active_hours', 'unenroll',
    'set_to_default_rate']

[metrics.unenroll.statistics.binomial]

## Set to default rate

[metrics.set_to_default_rate]
select_expression = "COALESCE(LOGICAL_OR(is_default_browser), FALSE)"
data_source = 'clients_daily'

[metrics.set_to_default_rate.statistics.binomial]