"""
This type stub file was generated by pyright.
"""

"""Private keys for the security serializer."""
__all__ = ("PrivateKey",)

class PrivateKey:
    """Represents a private key."""

    def __init__(self, key, password=...) -> None: ...
    def sign(self, data, digest):  # -> Any:
        """Sign string containing data."""
        ...
