"""
This type stub file was generated by pyright.
"""

"""Secure serializer."""
__all__ = ("SecureSerializer", "register_auth")

class SecureSerializer:
    """Signed serializer."""

    def __init__(
        self, key=..., cert=..., cert_store=..., digest=..., serializer=...
    ) -> None: ...
    def serialize(self, data):  # -> str:
        """Serialize data structure into string."""
        ...
    def deserialize(self, data):  # -> str:
        """Deserialize data structure from string."""
        ...

def register_auth(key=..., cert=..., store=..., digest=..., serializer=...):  # -> None:
    """Register security serializer."""
    ...
