from django.urls import re_path

from experimenter.nimbus_ui_new.views import (
    LaunchPreviewToDraftView,
    LaunchPreviewToReviewView,
    LaunchToPreviewView,
    LaunchWithoutPreviewView,
    MetricsUpdateView,
    NimbusChangeLogsView,
    NimbusExperimentDetailView,
    NimbusExperimentsCreateView,
    NimbusExperimentsListTableView,
    QAStatusUpdateView,
    SignoffUpdateView,
    SubscribeView,
    TakeawaysUpdateView,
    UnsubscribeView,
)

urlpatterns = [
    re_path(
        r"^(?P<slug>[\w-]+)/history/$",
        NimbusChangeLogsView.as_view(),
        name="nimbus-new-history",
    ),
    re_path(
        r"^table/",
        NimbusExperimentsListTableView.as_view(),
        name="nimbus-new-table",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/summary/$",
        NimbusExperimentDetailView.as_view(),
        name="nimbus-new-detail",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/update_qa_status/$",
        QAStatusUpdateView.as_view(),
        name="update-qa-status",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/update_takeaways/$",
        TakeawaysUpdateView.as_view(),
        name="update-takeaways",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/update_signoff/$",
        SignoffUpdateView.as_view(),
        name="update-signoff",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/update_metrics/$",
        MetricsUpdateView.as_view(),
        name="nimbus-new-update-metrics",
    ),
    re_path(
        r"^create/",
        NimbusExperimentsCreateView.as_view(),
        name="nimbus-new-create",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/subscribe/",
        SubscribeView.as_view(),
        name="nimbus-new-subscribe",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/unsubscribe/",
        UnsubscribeView.as_view(),
        name="nimbus-new-unsubscribe",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/launch-to-preview/$",
        LaunchToPreviewView.as_view(),
        name="launch-to-preview",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/launch-without-preview/$",
        LaunchWithoutPreviewView.as_view(),
        name="launch-without-preview",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/launch-preview-to-review/$",
        LaunchPreviewToReviewView.as_view(),
        name="launch-preview-to-review",
    ),
    re_path(
        r"^(?P<slug>[\w-]+)/launch-preview-to-draft/$",
        LaunchPreviewToDraftView.as_view(),
        name="launch-preview-to-draft",
    ),

]
