"""
This type stub file was generated by pyright.
"""

"""Task Annotations.

Annotations is a nice term for monkey-patching task classes
in the configuration.

This prepares and performs the annotations in the
:setting:`task_annotations` setting.
"""
_first_match = ...
_first_match_any = ...
__all__ = ("MapAnnotation", "prepare", "resolve_all")

class MapAnnotation(dict):
    """Annotation map: task_name => attributes."""

    def annotate_any(self): ...
    def annotate(self, task): ...

def prepare(annotations):  # -> tuple[()] | list[MapAnnotation | mlazy | Unknown]:
    """Expand the :setting:`task_annotations` setting."""
    ...

def resolve_all(anno, task):  # -> Generator[Unknown | Any, None, None]:
    """Resolve all pending annotations."""
    ...
