# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0002_project")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="dashboard_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="dashboard_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
