---
version: 1.0.0
about:
  description: Nimbus Feature Manifest for Monitor Web testing
channels:
  - staging
features:
  automatic-removal-csat-survey:
    description: Show the CSAT survey for Plus users that have automatically removed broker results
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: true
  last-scan-date:
    description: "Show the date of the user's last scan in the top right-hand corner"
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: true
  welcome-scan-optional-info:
    description: Show additional optional inputs to provide middle name and name suffix for broker scan
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: false
