"""
This type stub file was generated by pyright.
"""

"""Tasks auto-retry functionality."""

def add_autoretry_behaviour(task, **options):  # -> None:
    """Wrap task's `run` method with auto-retry functionality."""
    ...
