"""
This type stub file was generated by pyright.
"""

"""Backend selection."""
__all__ = ("by_name", "by_url")
UNKNOWN_BACKEND = ...
BACKEND_ALIASES = ...

def by_name(backend=..., loader=..., extension_namespace=...):  # -> Any:
    """Get backend class by name/alias."""
    ...

def by_url(backend=..., loader=...):  # -> tuple[Unknown | Any, Unknown | None]:
    """Get backend class by URL."""
    ...
