friendly_name = "Defaults and OS Integration"
description = """
    Measures changes to operation system (OS) placement such as
    launcher affordances and shell integrations.

    This outcome captures impacts to the default browser setting,
    other default app settings, and Windows pinning (and not
    subsequent behavourial changes due to such changes).
"""

[metrics.is_default_browser.statistics.binomial]
[metrics.is_default_pdf_handler.statistics.binomial]
[metrics.is_pinned.statistics.binomial]
