"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, TextIO

__author__ = ...

def print_provider(
    doc,
    provider: List[str],
    formatters: Dict[str, Any],
    excludes=...,
    output: Optional[TextIO] = ...,
) -> None: ...
def print_doc(
    provider_or_field=..., args=..., lang: str = ..., output=..., seed=..., includes=...
) -> None: ...

class Command:
    def __init__(self, argv=...) -> None: ...
    def execute(self) -> None:
        """
        Given the command-line arguments, this creates a parser appropriate
        to that command, and runs it.
        """
        ...

def execute_from_command_line(argv=...) -> None:
    """A simple method that runs a Command."""
    ...

if __name__ == "__main__": ...
