"""
This type stub file was generated by pyright.
"""

logger = ...
inREPL = ...
if inREPL: ...
else: ...

class Factory:
    @classmethod
    def create(
        cls,
        locale=...,
        providers=...,
        generator=...,
        includes=...,
        use_weighting=...,
        **config
    ): ...
