name: Schema Tests

on:
  push:
    branches:
      - main
      - external-config
      - update-application-services
      - update_firefox_desktop_release
      - update_firefox_desktop_beta
    paths:
      - "schemas/**"
      - ".github/workflows/check-schemas.yml"
  pull_request:
    paths:
      - "schemas/**"
      - ".github/workflows/check-schemas.yml"
  merge_group:
    types: [checks_requested]

jobs:
  check:
    name: "Check Schemas"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-cached-build

      - name: Run schemas tests and linting
        run: make schemas_check
