name: Cirrus Check

on:
  push:
    branches:
      - main
      - external-config
      - update-application-services
      - update_firefox_desktop_release
      - update_firefox_desktop_beta
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    name: "${{ matrix.arch }}"
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/check-changed-paths
        id: check-paths
        with:
          paths: "cirrus/ application-services/"

      - uses: ./.github/actions/setup-cached-build
        if: steps.check-paths.outputs.should-run == 'true'

      - name: Run Cirrus tests and linting
        if: steps.check-paths.outputs.should-run == 'true'
        run: |
          cp .env.sample .env
          make cirrus_check
