name: Cirrus Check

on:
  push:
    branches:
      - main
      - external-config
      - update-application-services
      - update_firefox_desktop_release
      - update_firefox_desktop_beta
    paths:
      - "cirrus/**"
      - "application-services/**"
      - ".github/workflows/check-cirrus.yml"
  pull_request:
    paths:
      - "cirrus/**"
      - "application-services/**"
      - ".github/workflows/check-cirrus.yml"
  merge_group:
    types: [checks_requested]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    name: "${{ matrix.arch }}"
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-cached-build

      - name: Run Cirrus tests and linting
        run: |
          cp .env.sample .env
          make cirrus_check
