name: Schema Tests

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  check:
    name: "Check Schemas"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: ./.github/actions/check-changed-paths
        id: check-paths
        with:
          paths: "schemas/"

      - uses: ./.github/actions/setup-cached-build
        if: steps.check-paths.outputs.should-run == 'true'

      - name: Run schemas tests and linting
        if: steps.check-paths.outputs.should-run == 'true'
        run: make schemas_check
