---
name: Glean probe-scraper
on: [push, pull_request]
jobs:
  glean-probe-scraper:
    if: github.repository == 'mozilla/experimenter'
    uses: mozilla/probe-scraper/.github/workflows/glean.yaml@975328bc197038a58e073d469bdab5c44692461a # main
