name: Remote Settings Launch Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  test:
    name: "Remote Settings Launch (All Applications)"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      FIREFOX_CHANNEL: release
      PYTEST_ARGS: -m remote_settings_launch --reruns 1 --base-url https://nginx/nimbus/
      PYTEST_BASE_URL: https://nginx/nimbus/
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/check-changed-paths
        id: check-paths
        with:
          paths: "experimenter/ application-services/"

      - uses: ./.github/actions/setup-cached-build
        if: steps.check-paths.outputs.should-run == 'true'

      - uses: ./.github/actions/run-integration-test
        if: steps.check-paths.outputs.should-run == 'true'
        with:
          artifact-name: remote-settings-launch-test-report
