name: Desktop Enrollment Integration Tests

on:
  push:
    branches:
      - main
      - external-config
      - update-application-services
      - update_firefox_desktop_release
      - update_firefox_desktop_beta
    paths:
      - "experimenter/**"
      - "application-services/**"
      - ".github/actions/run-integration-test/**"
      - ".github/workflows/integration-desktop-enrollment.yml"
  pull_request:
    paths:
      - "experimenter/**"
      - "application-services/**"
      - ".github/actions/run-integration-test/**"
      - ".github/workflows/integration-desktop-enrollment.yml"
  merge_group:
    types: [checks_requested]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        split: [0, 1]
    name: "Desktop Enrollment (${{ matrix.split }})"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      FIREFOX_CHANNEL: release
      PYTEST_ARGS: -k FIREFOX_DESKTOP -m desktop_enrollment --reruns 1 --splits 2 --split ${{ matrix.split }} --base-url https://nginx/nimbus/
      PYTEST_BASE_URL: https://nginx/nimbus/
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-cached-build

      - uses: ./.github/actions/run-integration-test
        with:
          artifact-name: desktop-enrollment-${{ matrix.split }}-test-report
