name: Desktop Targeting Integration Tests

on:
  push:
    branches:
      - main
      - external-config
      - update-application-services
      - update_firefox_desktop_release
      - update_firefox_desktop_beta
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        channel: [release, beta, nightly]
        split: [0, 1]
    name: "Desktop Targeting (${{ matrix.channel }} ${{ matrix.split }})"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      FIREFOX_CHANNEL: ${{ matrix.channel }}
      PYTEST_ARGS: -k FIREFOX_DESKTOP -m run_targeting -n 4 --reruns 1 --splits 2 --split ${{ matrix.split }} --base-url https://nginx/nimbus/
      PYTEST_BASE_URL: https://nginx/nimbus/
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/check-changed-paths
        id: check-paths
        with:
          paths: "experimenter/ application-services/"

      - uses: ./.github/actions/setup-cached-build
        if: steps.check-paths.outputs.should-run == 'true'

      - uses: ./.github/actions/run-integration-test
        if: steps.check-paths.outputs.should-run == 'true'
        with:
          make-args: FIREFOX_CHANNEL=${{ matrix.channel }}
          artifact-name: desktop-targeting-${{ matrix.channel }}-${{ matrix.split }}-test-report
