"""
This type stub file was generated by pyright.
"""

"""Creating events, and event exchange definition."""
__all__ = ("Event", "event_exchange", "get_exchange", "group_from")
EVENT_EXCHANGE_NAME = ...
event_exchange = ...

def Event(
    type, _fields=..., __dict__=..., __now__=..., **fields
):  # -> dict[Unknown, Unknown] | dict[str, Unknown]:
    """Create an event.

    Notes:
        An event is simply a dictionary: the only required field is ``type``.
        A ``timestamp`` field will be set to the current time if not provided.
    """
    ...

def group_from(type):
    """Get the group part of an event type name.

    Example:
        >>> group_from('task-sent')
        'task'

        >>> group_from('custom-my-event')
        'custom'
    """
    ...

def get_exchange(conn, name=...):  # -> Exchange:
    """Get exchange used for sending events.

    Arguments:
        conn (kombu.Connection): Connection used for sending/receiving events.
        name (str): Name of the exchange. Default is ``celeryev``.

    Note:
        The event type changes if Redis is used as the transport
        (from topic -> fanout).
    """
    ...
