"""
This type stub file was generated by pyright.
"""

import json

from graphene_django.views import GraphQLView

from ..utils import place_files_in_operations

"""Apply multipart request spec to django"""

class FileUploadGraphQLView(GraphQLView):
    """Handles multipart/form-data content type in django views"""

    def parse_body(self, request):  # -> Any | list[Unknown] | dict[Unknown, Unknown]:
        """Handle multipart request spec for multipart/form-data"""
        ...
