# Generated by Django 3.2.3 on 2021-06-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_auto_20210502_0608"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportlog",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
